version: "2"

services:
  mongodb:
    container_name: mongo.descartae
    image: mongo:3.4
    restart: always
    command: --smallfiles --noprealloc
    ports:
      - 27017:27017
    networks:
      - descartae

  webportal-server:
    container_name: server.webportal.descartae
    image: descartae/webportal-server
    command: npm run build:watch
    restart: always
    volumes:
      - ./server:/opt/app
      - /opt/app/node_modules
    ports:
      - 4000:4000
    environment:
      - SERVER_PORT=4000
      - JWT_SECRET=descartae
      - MONGODB_URL=mongodb://mongodb:27017/webportal
    networks:
      - descartae

  webportal-client:
    container_name: client.webportal.descartae
    image: descartae/webportal-client
    command: npm run build:watch
    restart: always
    volumes:
      - ./client:/opt/app
      - /opt/app/node_modules
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - REACT_APP_SERVER_URL=http://localhost:4000/graphql
    networks:
      - descartae

networks:
  descartae:
    driver: bridge
