version: "2"

services:
  webportal-client:
    container_name: client.webportal.descartae
    image: descartae/webportal-client
    command: npm run build:watch
    restart: always
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - REACT_APP_SERVER_URL=http://localhost:4000/graphql
    networks:
      - descartae

networks:
  descartae:
    driver: bridge
